language: python
dist: trusty
sudo: false
cache: pip
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36

before_script:
  - pip install -r test/requirements.txt
  - openssl aes-256-cbc -d -in config.xml.encrypted.1 -k ${KEY} -out config.xml

script: nosetests -v  --processes=4 --process-timeout=200 -c nose.config test/*.py

after_success:
  - travis_wait 120 python mpmain.py 6 config.xml
  - coverage report --omit '/home/travis/*'
  #- coveralls
