language: python
os: osx
dist: trusty
sudo: false
cache: pip
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36

before_script:
  - pip install -r test/requirements.txt
  - cp config.xml.dist config.xml

script: nosetests -v  --processes=4 --process-timeout=200 --with-coverage --cover-package pkg --cover-package pkg/queryGenerators --cover-package test --cover-package . --cover-package pkg/queryGenerators test/*.py

after_success:
  - coverage report --omit '/home/travis/virtualenv/python2.7.13/*,mpmain.py'
  #- coveralls
