version: 2.0

jobs:
  checkout_bing:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout

      - run:
          name: upgrade
          command: pip install --upgrade pip

      - run:
          name: ssl key
          command: openssl aes-256-cbc -d -in config.xml.encrypted -k "${KEY}" >> config.xml

      - run: 
          name: config
          command: chmod og-r config.xml

      - run:
          name: install update
          command: pip install -r requirements.txt
          
      # checking parallel runs https://discuss.circleci.com/t/parallel-runs-status/15876/2 and test file for highest timeout
      # https://github.com/dlanger/nose-parallel
      - run:
          name: reward unittest      
          command: coverage run -p --branch test/rewardtest.py

      - run:
          name: config unittest
          command: coverage run -p --branch test/configtest.py
      
      - run:
          name: unittest coverge merge  
          command: while ! coverage combine --debug=sys,trace; do echo "#"; done    
          # workaround for branch issue arc issue

      - run:
          name: run unittest report
          command: coverage report --omit '/home/ubuntu/*/*/*/*,/usr/*,mpmain.py'

      # comment out until coveralls support feature
      # - coveralls --rcfile=.coveragerc
      # need loving for nosetest to run without arc issue
      - run:
          name: erase coverage artifacts
          command: coverage erase
          
      - run:
          name: run with 4 processes code and test coverage
          command: nosetests -v  --processes=4 --process-timeout=200 --with-coverage --cover-package pkg --cover-package pkg/queryGenerators --cover-package test --cover-package . --cover-package pkg/queryGenerators test/*.py
          
      - run:
          name: save temp report
          command: cp .coverage .coverage.1

      # need more loving from circleci coverage plugin
      - run:
          name: run main code again to improver coverage
          command: coverage run -p main.py -v -r
  
      # combine with two processes running coverage seems broken
      - run:
          name: run main code
          command: coverage combine

      - run:
          name: run main code       
          command: rm -f config.xml          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_bing
