version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/python:2.7.10
    steps:
      - checkout

  test:
    docker:
      - image: circleci/python:2.7.10  
    steps:
      # checking parallel runs https://discuss.circleci.com/t/parallel-runs-status/15876/2 and test file for highest timeout
      # https://github.com/dlanger/nose-parallel
      - run: coverage run -p --branch test/rewardtest.py
      - run: coverage run -p --branch test/configtest.py
      # workaround for branch issue arc issue
      - run: while ! coverage combine --debug=sys,trace; do echo "#"; done
      - run: coverage report --omit '/home/ubuntu/*/*/*/*,/usr/*,mpmain.py'
      # comment out until coveralls support feature
      # - coveralls --rcfile=.coveragerc
      # need loving for nosetest to run without arc issue
      - run: ls .c*
      - run: coverage erase
      - run: nosetests -v  --processes=4 --process-timeout=200 --with-coverage --cover-package pkg --cover-package pkg/queryGenerators --cover-package test --cover-package . --cover-package pkg/queryGenerators test/*.py:
      - run: cp .coverage .coverage.1
      # need more loving from circleci coverage plugin
      - run: coverage run -p main.py -v -r
      # combine with two processes running coverage seems broken
      - run: coverage combine
      - run: rm -f config.xml

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    environment:
      - CODECLIMATE_REPO_TOKEN: b1bfad9809ef8b3be1eefa761352840a5ea632ef8bff0981fe295d61f9e2af84
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: openssl aes-256-cbc -d -in config.xml.encrypted -k "${KEY}" >> config.xml
      - run: chmod og-r config.xml
      - run: pip install -r requirements.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
  
      - deploy:
          requires:
            - test
