version: 2.0

jobs:
  checkout_bing:
    docker:
      - image: circleci/python:2.7.10
    steps:
      - checkout

  build:
    docker:
      - image: circleci/python:2.7.10  
    steps:
      # checking parallel runs https://discuss.circleci.com/t/parallel-runs-status/15876/2 and test file for highest timeout
      # https://github.com/dlanger/nose-parallel
      - run: coverage run -p --branch test/rewardtest.py
      - run: coverage run -p --branch test/configtest.py
      # workaround for branch issue arc issue
      - run: while ! coverage combine --debug=sys,trace; do echo "#"; done
      - run: coverage report --omit '/home/ubuntu/*/*/*/*,/usr/*,mpmain.py'
      # comment out until coveralls support feature
      # - coveralls --rcfile=.coveragerc
      # need loving for nosetest to run without arc issue
      - run: ls .c*
      - run: coverage erase
      - run: nosetests -v  --processes=4 --process-timeout=200 --with-coverage --cover-package pkg --cover-package pkg/queryGenerators --cover-package test --cover-package . --cover-package pkg/queryGenerators test/*.py:
      - run: cp .coverage .coverage.1
      # need more loving from circleci coverage plugin
      - run: coverage run -p main.py -v -r
      # combine with two processes running coverage seems broken
      - run: coverage combine
      - run: rm -f config.xml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_bing
      - build

